### ISSUE TITLE
RDX.asm:47: warning: word data exceeds bounds 

### ISSUE THREAD

**Issue by maxbendinelli** [SkyLined/alpha3#3]
When I try to buld the code , something is wrong with nasm...

...
== rm64 ==
  @ Reading build configuration.
  @ Version 1.0 alpha, build 53, started at Sun, 14 Jan 2018 21:07:04 (UTC)
  [x64\ascii\mixedcase\rm64]
    + Build: RDX.bin
      "C:\Users\XXXXX\AppData\Local\NASM\nasm.exe" "RDX.asm" -w+error -o "RDX.bin" -DBUILD_VERSION="None" -DBUILD_NUMBER="53" -DBUILD_TIMESTAMP="Sun, 14 Jan 2018 21:07:04 (UTC)" -DBUILD_PROJECT="x64\ascii\mixedcase\rm64" -f bin
      ERRORLEVEL = 1
  * C:\Users\XXXXXX\AppData\Local\NASM\nasm.exe returned error 1:
    |RDX.asm:47: warning: word data exceeds bounds
    |
    @ Project build failed.
@ Build failed.

**Comment by amittenak47** [comment]
I'm getting the same error when building. Did you ever end up resolving it?

EDIT:

It builds after changing each register *.ASM file to define 32 bit word

; %define INC_RSI_XOR_mult_value          dw B2W(0xFF, 0xC6) ^ mult_value ; INC RSI ^ mult_value
%define INC_RSI_XOR_mult_value          dd B2W(0xFF, 0xC6) ^ mult_value ; INC RSI ^ mult_value

**Comment by ziranan** [comment]
➜  alpha3 git:(master) ✗ python3 ALPHA3.py
Traceback (most recent call last):
  File "/home/ziran/Desktop/buu/alpha3/ALPHA3.py", line 4, in <module>
    import charsets, encode, io
  File "/home/ziran/Desktop/buu/alpha3/encode.py", line 1, in <module>
    import ALPHA3
  File "/home/ziran/Desktop/buu/alpha3/ALPHA3.py", line 5, in <module>
    import x86, x64, test
  File "/home/ziran/Desktop/buu/alpha3/x86/__init__.py", line 1, in <module>
    import ascii, latin_1, utf_16
ModuleNotFoundError: No module named 'ascii'
I don't konw why it is wrong,to repair it is very important for me
